/**
 * This file is generated by Phero.
 * https://github.com/phero-hq/phero
 * Do not edit this file by hand. Changes will be disregarded next time it's generated.
 **/

/* eslint-disable */
/* prettier-disable */

import { Fetch, BasePheroClient, ParseResult, ValidationError } from "@phero/client";
function error_parser_example(error: any): Error { if (error.name === "Error")
    return new Error(error.props.message);
else
    return new Error("Unknown Error"); }
export class PheroClient extends BasePheroClient {
    constructor(fetch: Fetch, url = "http://localhost:3030") { super(fetch, url); }
    example = {
        test: async (): Promise<void> => { return this.requestVoid("example", "test", {}, error_parser_example); }
    };
}
